owner: evolvepune
repo: website-status

assignees:
  - evolvepune
  - prateek-budhiraja

sites:
  - name: Evolve Pune
    url: https://evolvepune.com
  - name: Courses - Evolve Pune
    url: https://courses.evolvepune.com/learn/
  - name: Iskcon Hinjewadi
    url: https://iskconhinjewadi.com/

status-website:
  baseUrl: /website-status
  logoUrl: https://raw.githubusercontent.com/evolvepune/website-status/master/assets/tlogo.png
  name: Evolve Pune IT
  introTitle: "Evolve Pune web projects status page"
  introMessage: "Welcome to the status website for Evolve Pune. Here, you can view the real-time status and performance of all our websites in one place."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
