owner: evolvepune
repo: website-status

sites:
  - name: Evolve Pune
    url: https://www.evolvepune.com
  - name: Courses - Evolve Pune
    url: https://www.evolvepune.com
  - name: Iskcon Hinjewadi
    url: https://iskconhinjewadi.com/

status-website:
  baseUrl: /website-status
  logoUrl: https://raw.githubusercontent.com/evolvepune/website-status/master/assets/tlogo.png
  name: Evolve Pune IT
  introTitle: "This is a status page for all Evolve Pune web projects."
  introMessage: This page is generated through **upptime** [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
